-- Wiring only. Every removal and rewrite runs here, in data.lua, so the recycler's
-- data-updates sees the final recipe set. Order matters: definitions before the files that use them.
require("prototypes.categories")
require("prototypes.fluids")
require("prototypes.items")
require("prototypes.asteroid-chunks")
require("prototypes.asteroids")
require("prototypes.entities.heating-panel")
require("prototypes.entities.heat-boiler")
require("prototypes.entities.melter")
require("prototypes.entities.quantum-research-center")
require("prototypes.crushing-recipes")
require("prototypes.reprocessing-recipes")
require("prototypes.processing-recipes")
require("prototypes.recipe-rewrites")
require("prototypes.space-locations")
require("prototypes.space-connections")
require("prototypes.technology-additions")
require("prototypes.technology-modifications")
require("prototypes.removals-recipes")
require("prototypes.removals-entities")
require("prototypes.removals-technologies")
require("prototypes.removals-planets")
require("prototypes.surface-conditions")
require("prototypes.starter-pack")
require("prototypes.nauvis-stub")
