-- Deletes the vanilla recipes that have no source or no use on a platform-only map
-- (DESIGN.md section 7, names resolved to 2.1.17 in PLAN.md section 3.1). Runs in data.lua so
-- the recycler never generates a reverse recipe for any of them.

local removed =
{
  -- Planet chains with a live alternative
  "basic-oil-processing",
  "advanced-oil-processing",
  "molten-iron-from-lava",
  "molten-copper-from-lava",
  "ammoniacal-solution-separation",
  "scrap-recycling",
  "biolubricant",
  "bioplastic",
  "biosulfur",
  "burnt-spoilage",
  "rocket-fuel-from-jelly",
  "coal-synthesis",

  -- Gleba, biters, wood and fish
  "agricultural-tower",
  "agricultural-science-pack",
  "artificial-jellynut-soil",
  "artificial-yumako-soil",
  "overgrowth-jellynut-soil",
  "overgrowth-yumako-soil",
  "biochamber",
  "bioflux",
  "biolab",
  "captive-biter-spawner",
  "capture-robot-rocket",
  "copper-bacteria",
  "copper-bacteria-cultivation",
  "iron-bacteria",
  "iron-bacteria-cultivation",
  "fish-breeding",
  "jellynut-processing",
  "yumako-processing",
  "nutrients-from-bioflux",
  "nutrients-from-biter-egg",
  "nutrients-from-fish",
  "nutrients-from-spoilage",
  "nutrients-from-yumako-mash",
  "pentapod-egg",
  "tree-seed",
  "biter-egg",
  "spidertron",
  "wooden-chest",
  "shotgun",
  "combat-shotgun",
  "shotgun-shell",
  "piercing-shotgun-shell",
  "flamethrower-ammo",
  "flamethrower",

  -- Burners, vehicles, rockets and robot logistics
  "boiler",
  "stone-furnace",
  "steel-furnace",
  "burner-mining-drill",
  "burner-inserter",
  "electric-mining-drill",
  "big-mining-drill",
  "pumpjack",
  "offshore-pump",
  "car",
  "tank",
  "cannon-shell",
  "explosive-cannon-shell",
  "uranium-cannon-shell",
  "explosive-uranium-cannon-shell",
  "rail",
  "rail-ramp",
  "rail-support",
  "rail-signal",
  "rail-chain-signal",
  "train-stop",
  "locomotive",
  "cargo-wagon",
  "fluid-wagon",
  "artillery-wagon",
  "artillery-shell",
  "artillery-turret",
  "rocket-silo",
  "cargo-landing-pad",
  "landing-pad-unloading-bay",
  "rocket-part",
  "space-platform-starter-pack",
  "nuclear-fuel",
  "rocket-fuel",
  "landfill",
  "cliff-explosives",
  "land-mine",
  "flamethrower-turret",
  "lightning-rod",
  "lightning-collector",
  "roboport",
  "construction-robot",
  "logistic-robot",
  "active-provider-chest",
  "passive-provider-chest",
  "storage-chest",
  "buffer-chest",
  "requester-chest",
  "heating-tower",
  "personal-roboport-equipment",
  "personal-roboport-mk2-equipment",

  -- The three vanilla asteroid classes; the six new classes replace them
  "metallic-asteroid-crushing",
  "carbonic-asteroid-crushing",
  "oxide-asteroid-crushing",
  "advanced-metallic-asteroid-crushing",
  "advanced-carbonic-asteroid-crushing",
  "advanced-oxide-asteroid-crushing",
  "metallic-asteroid-reprocessing",
  "carbonic-asteroid-reprocessing",
  "oxide-asteroid-reprocessing"
}

local recipes = data.raw.recipe
for _, name in ipairs(removed) do
  recipes[name] = nil
end
